version: '3.8'
services:
  mongodb:
    image: mongo
    hostname: mongodb
    environment:
      NODE_ENV: 'production'
      MONGO_INITDB_ROOT_USERNAME: 'admin'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db # Mounts ./data/db directory on the host into /data/db directory in the container
    restart: always
  backend:
    build:
      context: .
    image: backend
    restart: always
    depends_on:
      - mongodb
    environment:
      PORT: 3000
      NODE_ENV: 'production'
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/moviedbprod
    ports:
      - 3000:3000